In [1]:
# 1. Function factorial with inner cache

def factorial(n, cache={}):
    if n <= 1:
        return 1
    
    if n in cache:
        print('reading from cache...', '%d! = %d' % (n, cache[n]))
        return cache[n]
    
    cache[n] = n * factorial(n-1)
    return cache[n]

print('9! =',factorial(9), '\n')
print('8! = ', factorial(8), '\n')
print('11! =', factorial(11), '\n')

9! = 362880 

reading from cache... 8! = 40320
8! =  40320 

reading from cache... 9! = 362880
11! = 39916800 



In [2]:
# 2. Function that takes an object and returns a dictionary with method names as keys
#    and the result of calling this methods as values.
#    Methods are all specified, except for double underscore (dunder) methods.
#    We suppose our methods don't require arguments.

class MyClass:
    def call_me_maybe(self):
        return 'I am called, yeeeah!!!'
    
    def call_me_too(self):
        return 'I am called too, yeaaah!!!'
    
    def dummy_number(self):
        return 5 + 7

def foo(obj):
    results = {}
    for func_name in dir(obj):
        if func_name.find('__') != 0:
            results[func_name] = getattr(obj, func_name)()
    return results

myobj = MyClass()
results = foo(myobj)

print(results)

{'call_me_maybe': 'I am called, yeeeah!!!', 'call_me_too': 'I am called too, yeaaah!!!', 'dummy_number': 12}


In [3]:
# 3. Class that defines objects, which represent a group of matrix rotations.
#    Define object multiplication by rewriting dunder method,
#    use singleton technique to reduce memory costs.
#    Every object of this class should be callable,
#    take a matrix and return a rotated matrix.

import numpy as np

def singleton(cls):
    def getinstance(angle):
        true_angle = angle % 360
        
        if not true_angle in [0, 90, 180, 270]:
            raise ValueError("Invalid angle. Angle can only be a multiple of 90")
        
        if not true_angle in cls.instances:
            cls.instances[true_angle] = cls(true_angle)
        return cls.instances[true_angle]
    return getinstance

@singleton
class Rotation:
    instances = {}
    
    def __init__(self, angle):
        print('creating %d deg rotation...\n' % angle)
        self.angle = angle % 360
        
    def __call__(self, matrix):
        matrix = np.array(matrix)
        
        if self.angle == 0:
            print('(rotating by 0 deg...)')
            return matrix
        
        if self.angle == 90:
            print('(rotating by 90 deg...)')
            return np.flip(matrix, 0).T
        
        if self.angle == 180:
            print('(rotating by 180 deg...)')
            return np.flip(np.flip(matrix, 0), 1)
        
        if self.angle == 270:
            print('(rotating by 270 deg...)')
            return np.flip(matrix.T, 0)
        
    def __mul__(self, other):
        return Rotation(self.angle + other.angle)
        
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('initial matrix: \n', m, '\n')

r0 = Rotation(0)
r90 = Rotation(90)
r180 = Rotation(180)
r270 = Rotation(270)

r450 = Rotation(450) # will not create a new object

print('clockwise rotation by 90 deg:')
print(r90(m), '\n')

print('clockwise rotation by 450 deg:')
print(r450(m), '\n')

print('clockwise rotation by r180 * r90 deg')
print((r180 * r90)(m), '\n')

initial matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

creating 0 deg rotation...

creating 90 deg rotation...

creating 180 deg rotation...

creating 270 deg rotation...

clockwise rotation by 90 deg:
(rotating by 90 deg...)
[[7 4 1]
 [8 5 2]
 [9 6 3]] 

clockwise rotation by 450 deg:
(rotating by 90 deg...)
[[7 4 1]
 [8 5 2]
 [9 6 3]] 

clockwise rotation by r180 * r90 deg
(rotating by 270 deg...)
[[3 6 9]
 [2 5 8]
 [1 4 7]] 



In [4]:
# 4. Write Singleton class

def singleton(cls):
    instances = {}
    def getinstance():
        if not cls in instances:
            instances[cls] = cls()
        return instances[cls]
    return getinstance

@singleton
class Singleton:
    def __init__(self):
        print('creating singleton')
            
a = Singleton()
b = Singleton()

print(a is b)

creating singleton
True
